//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akinator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AkinatorDatabaseEntities : DbContext
    {
        public AkinatorDatabaseEntities()
            : base("name=AkinatorDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<GameCharacterRank> GameCharacterRanks { get; set; }
        public virtual DbSet<QuestionCathegory> QuestionCathegories { get; set; }
        public virtual DbSet<QuestionCharacterConnection> QuestionCharacterConnections { get; set; }
        public virtual DbSet<QuestionCorelation> QuestionCorelations { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
    }
}
