//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akinator
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionCorelation
    {
        public int Id { get; set; }
        public int QuestionA { get; set; }
        public int QuestionB { get; set; }
        public Nullable<int> CommonCases { get; set; }
        public Nullable<int> CorelationPower { get; set; }
        public Nullable<int> CorelationDirection { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Question Question1 { get; set; }
    }
}
