//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akinator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.QuestionCharacterConnections = new HashSet<QuestionCharacterConnection>();
            this.QuestionCorelations = new HashSet<QuestionCorelation>();
            this.QuestionCorelations1 = new HashSet<QuestionCorelation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> QuestionCathegory { get; set; }
        public Nullable<int> GeneralizationDegree { get; set; }
    
        public virtual QuestionCathegory QuestionCathegory1 { get; set; }
        public virtual ICollection<QuestionCharacterConnection> QuestionCharacterConnections { get; set; }
        public virtual ICollection<QuestionCorelation> QuestionCorelations { get; set; }
        public virtual ICollection<QuestionCorelation> QuestionCorelations1 { get; set; }
    }
}
