//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akinator
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionCathegory
    {
        public QuestionCathegory()
        {
            this.QuestionCathegories1 = new HashSet<QuestionCathegory>();
            this.Questions = new HashSet<Question>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentCathegory { get; set; }
    
        public virtual ICollection<QuestionCathegory> QuestionCathegories1 { get; set; }
        public virtual QuestionCathegory QuestionCathegory1 { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
