//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akinator
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionCharacterConnection
    {
        public int Id { get; set; }
        public int Character { get; set; }
        public int Question { get; set; }
        public Nullable<double> ProbabilisticEvaluation { get; set; }
        public Nullable<int> OccurencesNumber { get; set; }
        public Nullable<int> YesAnswers { get; set; }
        public Nullable<int> ProbablyYesAnswers { get; set; }
        public Nullable<int> DontKnowAnswers { get; set; }
        public Nullable<int> ProbablyNotAnswers { get; set; }
        public Nullable<int> NotAnswers { get; set; }
    
        public virtual Character Character1 { get; set; }
        public virtual Question Question1 { get; set; }
    }
}
